[package]
name = "gguf_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.10"
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "cli"
path = "src/main.rs"